### ISSUE TITLE
Catching a fish with a full inventory causes a crash to desktop

### ISSUE THREAD

**Issue by randomname110101** [Ruin0x11/ElonaPlusCustom_GX#30] opened 2021-10-29 10:36 UTC
I was fishing when I noticed the game would consistently crash on the third fish caught. After clearing some room in my inventory I tried fishing again and it did not crash. Currently on the latest version.

**Comment by randomname110101** [comment] 2021-10-31 12:32
Oh, I noticed .1.1 released so I tried and successfully reproduced it, and got this error dump:
HspError 7 WinError 0 Line -1 Ver 6070 Mode 0
Message (JP): ”z—ñ‚Ì—v‘f‚ª–³Œø‚Å‚·
Message (EN): Array overflow
efId 185 efP 0 Area 7/1
ci 0 ti -1#574 cc 0#0 tc 0#0 rc 54#41
3. main_init:End ct:0
2. turn_end:pc ct:0
1. main_init:Begin ct:245
0. main_init:End ct:0
* ci is below 0

**Comment by Ruin0x11** [comment] 2021-12-13 04:16
I can't seem to reproduce this with the latest version of the code. The game correctly prevents fishing and indicates the inventory is full. It might be related to something other than the current inventory size.

If this still happens with 2.07.2.0, do reopen this issue so I can investigate further.

**Comment by randomname110101** [comment] 2021-12-13 05:14
Just tried again and it crashed again. Here's my save if you'd like to try to reproduce it. My steps: walk over to the water tile, mix water fleas with fishing rod, and fish for 6 hours. It eventually crashes when catching a fish with the same array overflow error.
[save.zip](https://github.com/Ruin0x11/ElonaPlusCustom-GX/files/7701128/save.zip)

**Comment by Ruin0x11** [comment] 2021-12-14 05:42
Turns out it had to do with the Super Lure. Interestingly, it's also a bug in stock Plus, but I guess nobody managed to trigger it up until now.

Fixed in 65500a3.

**Closed as completed by Ruin0x11** 2021-12-14 05:42 UTC
